### GET Solicitacoes
GET http://localhost:8080/api/v1/solicitacoes
Content-Type: application/json

### POST Solicitacoes
POST http://localhost:8080/api/v1/solicitacoes
Content-Type: application/json

{
  "id": " ",
  "data": " ",
  "horaInicio": " ",
  "horaFim": " ",
  "descricao": " "
}

### PUT Solicitacoes
PUT http://localhost:8080/api/v1/alunos/1
Content-Type: application/json

{
  "id": " ",
  "data": " ",
  "horaInicio": " ",
  "horaFim": " ",
  "descricao": " "
}

### DELETE Solicitacoes
DELETE http://localhost:8080/api/v1/alunos/1
Content-Type: application/json
